---
services:
  - docker

before_install:
  - cd docker
  - docker-compose -A

install:
  - docker-compose up -d

script:
  - docker ps 
  - ss -antps | grep 127.0.0.1:80 | grep LISTEN
  - ss -antps | grep 127.0.0.1:3306 | grep LISTEN
