mysql:
    image: mysql:5.6.34
    ports:
        - "127.0.0.1:3306:3306"
    volumes:
        - ./files/mysql:/var/lib/mysql/:rw

adminer:
    image: activatedgeek/adminer:latest
    ports:
        - "1284:80"
    links:
        - mysql

web:
    build: docker/httpd
    volumes:
        - ./files/html:/var/www/html:rw
    links:
        - mysql

nginx:
    image: nginx:latest
    ports:
        - "80:80"
    links: 
        - web

